### ISSUE TITLE
[1.10.2] NBT NPE on the alchemy table tileentity during save

### ISSUE THREAD

**Issue by Tamaized** [Tamaized/VoidCraft#125]
May also exist in 1.11.2
> A TileEntity type Tamaized.Voidcraft.machina.tileentity.TileEntityVoidicAlchemy has throw an exception trying to write state. It will not persist. Report this to the mod author
> java.lang.NullPointerException
> 	at Tamaized.Voidcraft.capabilities.vadeMecum.VadeMecumCapabilityStorage.writeNBT(VadeMecumCapabilityStorage.java:26) ~[VadeMecumCapabilityStorage.class:?]
> 	at Tamaized.Voidcraft.capabilities.vadeMecum.VadeMecumCapabilityStorage.writeNBT(VadeMecumCapabilityStorage.java:14) ~[VadeMecumCapabilityStorage.class:?]
> 	at net.minecraftforge.common.capabilities.Capability.writeNBT(Capability.java:108) ~[Capability.class:?]
> 	at Tamaized.Voidcraft.machina.tileentity.TileEntityVoidicAlchemy.writeNBT(TileEntityVoidicAlchemy.java:120) ~[TileEntityVoidicAlchemy.class:?]
> 	at Tamaized.TamModized.tileentity.TamTileEntity.func_189515_b(TamTileEntity.java:20) ~[TamTileEntity.class:?]
> 	at Tamaized.Voidcraft.api.voidicpower.TileEntityVoidicPower.func_189515_b(TileEntityVoidicPower.java:22) ~[TileEntityVoidicPower.class:?]
> 	at Tamaized.Voidcraft.api.voidicpower.TileEntityVoidicPowerInventory.func_189515_b(TileEntityVoidicPowerInventory.java:42) ~[TileEntityVoidicPowerInventory.class:?]
> 	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:384) [atj.class:?]
> 	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:175) [atj.class:?]
> 	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:199) [lr.class:?]
> 	at net.minecraft.world.gen.ChunkProviderServer.func_186027_a(ChunkProviderServer.java:227) [lr.class:?]
> 	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1013) [ls.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:355) [MinecraftServer.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:393) [MinecraftServer.class:?]
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
> 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]

**Comment by Tamaized** [comment]
Was caused by having the table owner set then the owner gained a new infusion ability.

**Comment by Tamaized** [comment]
Based on what I can see from just looking at my code through github, this doesnt exist in 1.11.2 as ItemStack.EMPTY is a thing, here the ItemStacks are null but arent being handled correctly.

https://github.com/Tamaized/VoidCraft/blob/1.10.2/src/main/java/Tamaized/Voidcraft/capabilities/vadeMecum/VadeMecumCapabilityStorage.java#L26

**Comment by Tamaized** [comment]
possible solution:
Check if the stack is empty/null, if so write "null" to the tag during Write.
During Read: check if the value is equal to "null" if so then we set the stack to Empty/null else do the normal ItemStack calls for NBT reading.

**Comment by Tamaized** [comment]
true cause after actually looking into this: Caused by removing stacks from the spells GUI and only when a set alchemy table exists.
