### ISSUE TITLE
Recurring crash in Xia's room.

### ISSUE THREAD

**Issue by KingEdward9830** [Tamaized/VoidCraft#193]
I walked into Xia's room, using the latest of Forge, TamModized and Voidcraft and nothing else. I hit a Hole in Reality on the way in and it teleported me to the castle entrance, but Xia's room was still open. I went back in, and now this happens when I try to load the world:
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 8/27/17 11:52 AM
Description: Ticking entity

java.lang.AbstractMethodError: tamaized.voidcraft.common.entity.boss.xia.ai.EntityAIXia1Phase1.shouldExecute()Z
	at tamaized.voidcraft.common.entity.boss.xia.EntityBossXia.func_70097_a(EntityBossXia.java:147)
	at tamaized.voidcraft.common.entity.boss.xia.EntityBossXia.func_82167_n(EntityBossXia.java:155)
	at net.minecraft.entity.EntityLivingBase.func_85033_bc(EntityLivingBase.java:2453)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2383)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at tamaized.voidcraft.common.entity.EntityVoidNPC.func_70636_d(EntityVoidNPC.java:134)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2166)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at tamaized.voidcraft.common.entity.EntityVoidNPC.func_70071_h_(EntityVoidNPC.java:175)
	at net.minecraft.world.World.func_72866_a(World.java:1983)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:833)
	at net.minecraft.world.World.func_72870_g(World.java:1945)
	at net.minecraft.world.World.func_72939_s(World.java:1755)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:614)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at tamaized.voidcraft.common.entity.boss.xia.EntityBossXia.func_70097_a(EntityBossXia.java:147)
	at tamaized.voidcraft.common.entity.boss.xia.EntityBossXia.func_82167_n(EntityBossXia.java:155)
	at net.minecraft.entity.EntityLivingBase.func_85033_bc(EntityLivingBase.java:2453)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2383)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at tamaized.voidcraft.common.entity.EntityVoidNPC.func_70636_d(EntityVoidNPC.java:134)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2166)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at tamaized.voidcraft.common.entity.EntityVoidNPC.func_70071_h_(EntityVoidNPC.java:175)
	at net.minecraft.world.World.func_72866_a(World.java:1983)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:833)
	at net.minecraft.world.World.func_72870_g(World.java:1945)

-- Entity being ticked --
Details:
	Entity Type: voidcraft:xia (tamaized.voidcraft.common.entity.boss.xia.EntityBossXia)
	Entity ID: 413
	Entity Name: entity.xia.name
	Entity's Exact location: 52.50, 92.50, 128.50
	Entity's Block location: World: (52,92,128), Chunk: (at 4,5,0 in 3,8; contains blocks 48,0,128 to 63,255,143), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1755)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:614)

-- Affected level --
Details:
	Level name: Test
	All players: 1 total; [EntityPlayerMP['EdwardSteve9830'/406, l='Test', x=50.17, y=77.07, z=91.80]]
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: 5839968936133354996
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.1
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 193334312 bytes (184 MB) / 548868096 bytes (523 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.41 Powered by Forge 14.22.0.2462 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID         | Version      | Source                        | Signature                                |
	|:--------- |:---------- |:------------ |:----------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft  | 1.12.1       | minecraft.jar                 | None                                     |
	| UCHIJAAAA | mcp        | 9.19         | minecraft.jar                 | None                                     |
	| UCHIJAAAA | FML        | 8.0.99.99    | forge-1.12.1-14.22.0.2462.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge      | 14.22.0.2462 | forge-1.12.1-14.22.0.2462.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | tammodized | 0.14.1       | TamModized-1.12.1-0.14.1.jar  | None                                     |
	| UCHIJAAAA | voidcraft  | 0.25.3       | VoidCraft-1.12.1-0.25.3.jar   | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['EdwardSteve9830'/406, l='Test', x=50.17, y=77.07, z=91.80]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Tamaized** [comment]
Not quite sure how that specific crash was possible but I'll look into it when I have time.

**Comment by KingEdward9830** [comment]
I got another crash when messing around with spells in the book, but I found a workaround to that one and unlike this one it's not a recurring crash. I'll post the log in a separate issue if you like, also I was wondering. 
If you have an existing world with a few mods on it already, and you're reasonably far but haven't gotten to the End yet, is this mod OK to add to that world? I'd obviously make a backup somewhere, but I just wondered since the End won't have generated yet and so the crystal ores should spawn right if they use the normal mechanics...

**Comment by Tamaized** [comment]
Go ahead and post the new crash in another issue as these two arent related.

As for the gen in the end issue, it's perfectly fine as the crystals will gen everywhere in the end and not just on the main island. End Generation isnt limited anymore like it used to be, it'll keep genning as you keep going out.

**Comment by KingEdward9830** [comment]
It's a good thing the world I was on was just a test world, I'm going to see if not stepping into a Hole in Reality right at the start of the fight solves the issue. My best guess based on what I saw is that Xia was right in the middle of spawning when I was warped back to the castle entrance. I will come back and comment again on this issue to tell you whether or not I successfully got into the fight.

**Comment by KingEdward9830** [comment]
Well, I actually got into the fight, but as soon as I was done with phase 1(I cheated to speed things up) the boss teleported to the center of the room and my game crashed again. I will check if it's the same error log. By the way, is Xia missing sound effects currently? Because I heard nothing when hitting him. Not even the usual sword sweep sound(except on the last hit which was weird).

**Comment by Tamaized** [comment]
Feel free to post the new log in this issue, use pastebin/gist if you can though

**Comment by Tamaized** [comment]
Alright I believe I tracked down what's going on here. Will get a fix out soon.

**Comment by KingEdward9830** [comment]
Thanks for the fast fixes, I'll let you know if any more issues come up while playing with this mod.
