### ISSUE TITLE
Issue with Biome Tweaker

### ISSUE THREAD

**Issue by Zygus42** [Tamaized/VoidCraft#46]
Getting the following crash during world gen:

> [21:34:01] [Server thread/ERROR] [FML]: Fatal errors were detected during the transition from AVAILABLE to SERVER_ABOUT_TO_START. Loading cannot continue
[21:34:01] [Server thread/ERROR] [FML]:
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
UCHIJAA mcp{9.19} Minecraft Coder Pack
UCHIJAA FML{8.0.99.99} Forge Mod Loader
UCHIJAA Forge{12.18.1.2095} Minecraft Forge
UCHIJAA Baubles{1.2.1.0} Baubles
UCHIJAA Botania{r1.9-328} Botania
UCHIJAA AkashicTome{1.0-4} Akashic Tome
UCHIJAA ArmorDamageRecalc{1.2} Armor Damage Recalc
UCHIJAA basemetals{2.4.0} Base Metals
UCHIJAA golems{6.02} Extra Golems
UCHIJAA golems_metal{6.02.1} Base Metal Golems
UCHIJAA hud{1.3.8} Better HUD
UCHIJEE BiomeTweaker{2.1.225} BiomeTweaker
UCHIJAA BiomesOPlenty{5.0.0.2086} Biomes O' Plenty
UCHIJAA botanicaladdons{GRADLE:VERSION.GRADLE:BUILD} Natural Pledge
UCHIJAA chickens{1.9.4-3.0} Chickens
UCHIJAA chisel{MC1.9.4-0.0.6.48} Chisel
UCHIJAA combathelp{1.0.3} Combat Help
UCHIJAA coralreef{1.0} Coral Reef
UCHIJAA MineTweaker3{3.0.12} MineTweaker 3
UCHIJAA modtweaker{2.0.4} Mod Tweaker
UCHIJAA mantle{1.10.2-1.0.0.jenkins170} Mantle
UCHIJAA tconstruct{1.10.2-2.5.3.jenkins387} Tinkers' Construct
UCHIJAA immersiveengineering{0.10-44} Immersive Engineering
UCHIJAA JEI{3.12.5.303} Just Enough Items
UCHIJAA guideapi{@VERSION@} Guide-API
UCHIJAA crossroads{1.10.2-1.1.4} Crossroads
UCHIJAA cyberware{beta-0.2.3} Cyberware
UCHIJAA disenchanter{1.4} Disenchanter
UCHIJAA dooglamoocitiesmod{1.10.2-1.1} Dooglamoo Cities Mod
UCHIJAA DragonMounts{r46-1.10.2} Dragon Mounts
UCHIJAA lootablebodies{2.2.0} DrCyano's Lootable Bodies
UCHIJAA ea{v2.4.7a-mc1.10.2} Ebon Arts
UCHIJAA EnderBags{2.0.1} EnderBags
UCHIJAA valkyrielib{1.10.2-0.10.4} Valkyrie Lib
UCHIJAA environmentaltech{1.10.2-0.10.4b} Environmental Tech
UCHIJAA expandablebackpack{1.1} Expandable Backpacks
UCHIJAA extraalchemy{0.3.0.2-release} Extra Alchemy
UCHIJAA flatcoloredblocks{mc1.10-v4.2} Flat Colored Blocks
UCHIJAA flowercraftmod{6.01} Flowercraft
UCHIJAA PreFoliage{0.9.0 Beta} PreFoliage
UCHIJAA forestry{5.2.14.263} Forestry
UCHIJAA glasscraftmod{1.0} Glasscraft
UCHIJAA helpertools{v3.0c} HelperTools
UCHIJAA JEFB{1.0.4} Just Enough Forestry Bees
UCHIJAA journeymap{1.10.2-5.3.0b1} JourneyMap
UCHIJAA lightningcraft{2.5.2} LightningCraft
UCHIJAA lit{@VERSION@} Little Insignificant Things
UCHIJAA mcmultipart{1.2.0_74} MCMultiPart
UCHIJAA Mekanism{9.2.0} Mekanism
UCHIJAA MekanismGenerators{9.2.0} MekanismGenerators
UCHIJAA MekanismTools{9.2.0} MekanismTools
UCHIJAA mikedongles{0.3.1} Mike Dongles
UCHIJAA moreanvils{6.0.2.11} More Anvils
UCHIJAA morebees{1.10.2-1.1.3} More Bees
UCHIJAA moreoverlays{1.8} MoreOverlays
UCHIJAA moreshears{1.0.0} More Shears
UCHIJAA mysticalagriculture{1.2.4} Mystical Agriculture
UCHIJAA natura{1.10.2-4.0.0.81} Natura
UCHIJAA netherportalfix{1.0} Nether Portal Fix
UCHIJAA recipehandler{0.5} NoMoreRecipeConflict
UCHIJAA fodc{1.9.1} Ore Dictionary Converter
UCHIJAA orespawn{1.1.0} Ore Spawn
UCHIJAA harvestcraft{1.9.4-1.10.2e} Pam's HarvestCraft
UCHIJAA placemod{3.8} Placemod
UCHIJAA planttech{1.7.3} Planttech
UCHIJAA Psi{r1.0-40} Psi
UCHIJAA psionup{GRADLE:VERSION.GRADLE:BUILD} PSIonic Upgrades
UCHIJAA Quark{r1.0-56} Quark
UCHIJAA AutoRegLib{1.0-2} AutoRegLib
UCHIJAA railcraft{10.0.0-beta-2} Railcraft
UCHIJAA randomthings{3.7.6} Random Things
UCHIJAA redstonepaste{1.7.4} Redstone Paste
UCHIJAA reptilemod{3.5.2} Reptile Mod
UCHIJAA rftools{5.50} RFTools
UCHIJAA Roguelike{1.5.4} Roguelike Dungeons
UCHIJAA roots{0.204} Roots
UCHIJAA RTG{1.10.2} Realistic Terrain Generation
UCHIJAA safejoin{1.3} SafeJoin
UCHIJAA LunatriusCore{1.1.2.36} LunatriusCore
UCHIJAA Schematica{1.7.8.152} Schematica
UCHIJAA cxlibrary{1.2.2} CXLibrary
UCHIJAA sensorcraft{0.4.0} SensorCraft
UCHIJAA shearmadness{1.10.2} Shear Madness
UCHIJAA Signals{1.0} Signals
UCHIJAA signpic{2.1.5} SignPicture
UCHIJAA SilentLib{1.0.12} Silent Lib
UCHIJAA WIT{1.0.20} WIT
UCHIJAA SilentGems{2.0.33} Silent's Gems
UCHIJAA gemulation{1.10-4.0.0} Gemulation
UCHIJAA Chameleon{1.10-2.1.7} Chameleon
UCHIJAA StorageDrawers{1.10.2-3.2.7} Storage Drawers
UCHIJAA Farseek{1.9.4} Farseek
UCHIJAA Streams{1.9.4} Streams
UCHIJAA thutcore{3.5.1} ThutCore
UCHIJAA thuttech{4.0.5} Thut's Tech
UCHIJAA trashslot{6.3.6} TrashSlot
UCHIJAA UndergroundOcean{${version}} Underground Ocean
UCHIJAA vc{v2.0.0a-mc1.10.2} ViesCraft
UCHIJAA villagebox{0.5.0} Village Box
UCHIJAA tammodized{0.2.2} TamModized
UCHIJAA voidcraft{0.9.5} VoidCraft
UD BiomeTweakerCore{2.1.225} BiomeTweaker Core
[21:34:01] [Server thread/ERROR] [FML]: The following problems were captured during this phase
[21:34:01] [Server thread/ERROR] [FML]: Caught exception from BiomeTweaker
java.io.IOException: The filename, directory name, or volume label syntax is incorrect
at java.io.WinNTFileSystem.createFileExclusively(Native Method) ~[?:1.8.0_101]
at java.io.File.createNewFile(Unknown Source) ~[?:1.8.0_101]
at me.superckl.biometweaker.BiomeTweaker.generateOutputFiles(BiomeTweaker.java:238) ~[BiomeTweaker.class:?]
at me.superckl.biometweaker.BiomeTweaker.onLoadComplete(BiomeTweaker.java:211) ~[BiomeTweaker.class:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:597) ~[forge-1.10.2-12.18.1.2095.jar:?]
at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239) ~[LoadController.class:?]
at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217) ~[LoadController.class:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142) ~[LoadController.class:?]
at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:798) ~[Loader.class:?]
at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:324) ~[FMLClientHandler.class:?]
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520) ~[bcx.class:?]
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351) ~[bcx.class:?]
at net.minecraft.client.main.Main.main(SourceFile:124) ~[1.10.2.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) ~[launchwrapper-1.12.jar:?]
at net.minecraft.launchwrapper.Launch.main(Launch.java:28) ~[launchwrapper-1.12.jar:?]
[21:34:01] [Server thread/ERROR] [FML]: A fatal exception occurred during the server about to start event
net.minecraftforge.fml.common.LoaderException: java.io.IOException: The filename, directory name, or volume label syntax is incorrect

at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:186) ~[LoadController.class:?]
at net.minecraftforge.fml.common.Loader.serverAboutToStart(Loader.java:911) [Loader.class:?]
at net.minecraftforge.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:287) [FMLCommonHandler.class:?]
at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:119) [bzl.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]

Caused by: java.io.IOException: The filename, directory name, or volume label syntax is incorrect
at java.io.WinNTFileSystem.createFileExclusively(Native Method) ~[?:1.8.0_101]
at java.io.File.createNewFile(Unknown Source) ~[?:1.8.0_101]
at me.superckl.biometweaker.BiomeTweaker.generateOutputFiles(BiomeTweaker.java:238) ~[BiomeTweaker.class:?]
at me.superckl.biometweaker.BiomeTweaker.onLoadComplete(BiomeTweaker.java:211) ~[BiomeTweaker.class:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:597) ~[forge-1.10.2-12.18.1.2095.jar:?]
at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239) ~[LoadController.class:?]
at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217) ~[LoadController.class:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142) ~[LoadController.class:?]
at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:798) ~[Loader.class:?]
at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:324) ~[FMLClientHandler.class:?]
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520) ~[bcx.class:?]
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351) ~[bcx.class:?]
at net.minecraft.client.main.Main.main(SourceFile:124) ~[1.10.2.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) ~[launchwrapper-1.12.jar:?]
at net.minecraft.launchwrapper.Launch.main(Launch.java:28) ~[launchwrapper-1.12.jar:?]
[21:34:01] [Server thread/INFO]: Stopping server
[21:34:01] [Server thread/INFO]: Saving players
[21:34:01] [Server thread/INFO]: Saving worlds

**Comment by Tamaized** [comment]
This is Biome Tweaker's issue, send it to them

**Comment by superckl** [comment]
It's actually caused by you using characters in your biome name that can't be written as file names...

```
new BiomeProperties("???")
```

I'll account for this on my side I suppose.

**Comment by Tamaized** [comment]
Would be best as other mods with special characters in their biome names wouldn't work either
