### ISSUE TITLE
[1.10.2] Incompatability with Menu Mobs

### ISSUE THREAD

**Issue by Cat-McCatface** [Tamaized/VoidCraft#53]
(note this is a cross post from Menu Mobs' issue tracker since that dev hasn't commented or closed it yet)

Both mods seem to be interact through the renderPlayer code causing MM to refuse to work (although gracefully fail instead of crash the client)

Forge 2094
Menu Mobs: 1.10.1
VoidCraft: 0.9.2 (I think, the test was 2 weeks ago)

error in log
```
[03:56:45] [Client thread/ERROR] [FML/]: 7: ASM: Tamaized.Voidcraft.voidicInfusion.client.RenderVoidicInfusion@3ab3b1fe renderPlayer(Lnet/minecraftforge/client/event/RenderPlayerEvent$Pre;)V
[03:56:45] [Client thread/ERROR] [menumobs/]: Main menu mob rendering encountered a serious error and has been disabled for the remainder of this session.
[03:56:45] [Client thread/INFO] [STDERR/]: [superbas11.menumobs.MainMenuRenderTicker:onTick:460]: net.minecraft.util.ReportedException: Rendering entity in world
[03:56:45] [Client thread/INFO] [STDERR/]: [superbas11.menumobs.MainMenuRenderTicker:onTick:460]:   at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:408)
[03:56:45] [Client thread/INFO] [STDERR/]: [superbas11.menumobs.MainMenuRenderTicker:onTick:460]:   at superbas11.menumobs.client.util.EntityUtils.drawEntityOnScreen(EntityUtils.java:175)
[03:56:45] [Client thread/INFO] [STDERR/]: [superbas11.menumobs.MainMenuRenderTicker:onTick:460]:   at superbas11.menumobs.MainMenuRenderTicker.onTick(MainMenuRenderTicker.java:444)
[03:56:45] [Client thread/INFO] [STDERR/]: [superbas11.menumobs.MainMenuRenderTicker:onTick:460]:   at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_610_MainMenuRenderTicker_onTick_RenderTickEvent.invoke(.dynamic)
[03:56:45] [Client thread/INFO] [STDERR/]: [superbas11.menumobs.MainMenuRenderTicker:onTick:460]:   at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[03:56:45] [Client thread/INFO] [STDERR/]: [superbas11.menumobs.MainMenuRenderTicker:onTick:460]:   at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
[03:56:45] [Client thread/INFO] [STDERR/]: [superbas11.menumobs.MainMenuRenderTicker:onTick:460]:   at net.minecraftforge.fml.common.FMLCommonHandler.onRenderTickStart(FMLCommonHandler.java:350)
[03:56:45] [Client thread/INFO] [STDERR/]: [superbas11.menumobs.MainMenuRenderTicker:onTick:460]:   at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1074)
[03:56:45] [Client thread/INFO] [STDERR/]: [superbas11.menumobs.MainMenuRenderTicker:onTick:460]:   at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
[03:56:45] [Client thread/INFO] [STDERR/]: [superbas11.menumobs.MainMenuRenderTicker:onTick:460]:   at net.minecraft.client.main.Main.main(SourceFile:124)
[03:56:45] [Client thread/INFO] [STDERR/]: [superbas11.menumobs.MainMenuRenderTicker:onTick:460]:   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[03:56:45] [Client thread/INFO] [STDERR/]: [superbas11.menumobs.MainMenuRenderTicker:onTick:460]:   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[03:56:45] [Client thread/INFO] [STDERR/]: [superbas11.menumobs.MainMenuRenderTicker:onTick:460]:   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[03:56:45] [Client thread/INFO] [STDERR/]: [superbas11.menumobs.MainMenuRenderTicker:onTick:460]:   at java.lang.reflect.Method.invoke(Unknown Source)
[03:56:45] [Client thread/INFO] [STDERR/]: [superbas11.menumobs.MainMenuRenderTicker:onTick:460]:   at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[03:56:45] [Client thread/INFO] [STDERR/]: [superbas11.menumobs.MainMenuRenderTicker:onTick:460]:   at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by Tamaized** [comment]
Anything higher up in the log just before this? Can't tell if it's a NPE or not, either way it's failing at `superbas11.menumobs.client.util.EntityUtils.drawEntityOnScreen` so there really isn't much I can do on my end

**Comment by Tamaized** [comment]
Actually, I looked into his code and my guess is the world is null which would cause the error on my end if I'm correct. I'll see if I can fix it

**Comment by Tamaized** [comment]
Confirmed to my end via NPE at
`Tamaized.Voidcraft.voidicInfusion.client.RenderVoidicInfusion.renderPlayer(RenderVoidicInfusion.java:23)`
Working on a fix
